package com.wholesale.platform.entity.enums;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    REGISTRATION,
    PASSWORD_CHANGE,
    OTP_VERIFICATION,
    PRODUCT_CREATION,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
    INVENTORY_CHANGE,
    ORDER_CREATION,
    ORDER_UPDATE,
    USER_CREATION,
    USER_UPDATE,
    ROLE_ASSIGNMENT,
    ACCOUNT_SUSPENSION,
    ACCOUNT_ACTIVATION,
    ACCOUNT_RESTORE,
    SECURITY_EVENT,
    SYSTEM_SETTING_CHANGE
}
